### ISSUE TITLE
kill iml and .idea from the repo

### ISSUE THREAD

**Issue by rogerhu** [codepath/android-booksearch-exercise#1]
I think it should be left out with gitignore given it can have directories specific to your machine.  Studio should regenerate it if it's missing.

**Comment by nidhi1608** [comment]
Done.

**Comment by rogerhu** [comment]
.idea is still there in the repo though?

**Comment by nidhi1608** [comment]
Should be fixed now.

**Comment by nesquena** [comment]
In general, we should use this more comprehensive [gitignore](https://gist.githubusercontent.com/nesquena/5617544/raw/e6b9ae7d168fd1f1a20b0ae88722c6134baa3ff6/.gitignore) for android repos. Some of it could be removed since it's eclipse specific but it helps avoid all the intermediate and unnecessary files in an android app.
